[package]
name = "image2ascii"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "*"
image = "*"
ffmpeg-next = "*"
bincode = "*"
serde = "*"
serde_derive = "*"
rodio = "*"
binrw = "*"
flate2 = "*"
